/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-12-14 12:48:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_002ddetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1606388403724L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1607843743963L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/ecommerce/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ecommerce/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1607843743906L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/ecommerce/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ecommerce/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("        ");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Chi tiết sản phẩm</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("<!-- Breadcrumb Section Begin -->\r\n");
      out.write("<div class=\"breacrumb-section\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("                <div class=\"breadcrumb-text\">\r\n");
      out.write("                    <a href = \"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"><i class=\"fa fa-home\"></i> Trang chủ</a>\r\n");
      out.write("                    <span>Chi tiết sản phẩm</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Breadcrumb Section End -->\r\n");
      out.write("\r\n");
      out.write("<!-- Product Shop Section Begin -->\r\n");
      out.write("<section class=\"product-shop spad page-details\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-3\">\r\n");
      out.write("                <div class=\"filter-widget\">\r\n");
      out.write("                        <h4 class=\"fw-title\">Dành cho:</h4>\r\n");
      out.write("                        <ul class=\"filter-catagories\">\r\n");
      out.write("                            <li><a href=\"#\">Nam</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Nữ</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Trẻ Em</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"filter-widget\">\r\n");
      out.write("                        <h4 class=\"fw-title\">Nhãn <Hiệu></Hiệu></h4>\r\n");
      out.write("                        <div class=\"fw-brand-check\">\r\n");
      out.write("                            <div class=\"bc-item\">\r\n");
      out.write("                                <label for=\"bc-calvin\">\r\n");
      out.write("                                    Yame\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"bc-calvin\">\r\n");
      out.write("                                    <span class=\"checkmark\"></span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"bc-item\">\r\n");
      out.write("                                <label for=\"bc-diesel\">\r\n");
      out.write("                                    Routine\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"bc-diesel\">\r\n");
      out.write("                                    <span class=\"checkmark\"></span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"bc-item\">\r\n");
      out.write("                                <label for=\"bc-polo\">\r\n");
      out.write("                                    Just Men\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"bc-polo\">\r\n");
      out.write("                                    <span class=\"checkmark\"></span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"filter-widget\">\r\n");
      out.write("                        <h4 class=\"fw-title\">Giá</h4>\r\n");
      out.write("                        <div class=\"filter-range-wrap\">\r\n");
      out.write("                            <div class=\"range-slider\">\r\n");
      out.write("                                <div class=\"price-input\">\r\n");
      out.write("                                    <div class=\"input-group mb-3\">\r\n");
      out.write("                                        <input name=\"price\" type=\"text\" class=\"form-control\" placeholder=\"Giá từ\" >\r\n");
      out.write("                                        <div class=\"input-group-append\">\r\n");
      out.write("                                            <span class=\"input-group-text\" id=\"basic-addon2\">đ</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"input-group mb-3\">\r\n");
      out.write("                                        <input  name=\"price\" type=\"text\" class=\"form-control\" placeholder=\"Đến\" >\r\n");
      out.write("                                        <div class=\"input-group-append\">\r\n");
      out.write("                                            <span class=\"input-group-text\" id=\"basic-addon1\">đ</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"price-range ui-slider ui-corner-all ui-slider-horizontal ui-widget ui-widget-content\"\r\n");
      out.write("                            data-min=\"33\" data-max=\"98\">\r\n");
      out.write("                            <div class=\"ui-slider-range ui-corner-all ui-widget-header\"></div>\r\n");
      out.write("                            <span tabindex=\"0\" class=\"ui-slider-handle ui-corner-all ui-state-default\"></span>\r\n");
      out.write("                            <span tabindex=\"0\" class=\"ui-slider-handle ui-corner-all ui-state-default\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#\" class=\"filter-btn\">Lọc</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"filter-widget\">\r\n");
      out.write("                    <h4 class=\"fw-title\">Màu Sắc</h4>\r\n");
      out.write("                    <div class=\"fw-color-choose\">\r\n");
      out.write("                        <div class=\"cs-item\">\r\n");
      out.write("                            <input type=\"radio\" id=\"cs-black\">\r\n");
      out.write("                            <label class=\"cs-black\" for=\"cs-black\">Đen</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"cs-item\">\r\n");
      out.write("                            <input type=\"radio\" id=\"cs-violet\">\r\n");
      out.write("                            <label class=\"cs-violet\" for=\"cs-violet\">Tím</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"cs-item\">\r\n");
      out.write("                            <input type=\"radio\" id=\"cs-blue\">\r\n");
      out.write("                            <label class=\"cs-blue\" for=\"cs-blue\">Xanh</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"cs-item\">\r\n");
      out.write("                            <input type=\"radio\" id=\"cs-yellow\">\r\n");
      out.write("                            <label class=\"cs-yellow\" for=\"cs-yellow\">Vàng</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"cs-item\">\r\n");
      out.write("                            <input type=\"radio\" id=\"cs-red\">\r\n");
      out.write("                            <label class=\"cs-red\" for=\"cs-red\">Đỏ</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"cs-item\">\r\n");
      out.write("                            <input type=\"radio\" id=\"cs-green\">\r\n");
      out.write("                            <label class=\"cs-green\" for=\"cs-green\">Xanh Lá</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"filter-widget\">\r\n");
      out.write("                    <h4 class=\"fw-title\">Size</h4>\r\n");
      out.write("                    <div class=\"fw-size-choose\">\r\n");
      out.write("                        <div class=\"sc-item\">\r\n");
      out.write("                            <input type=\"radio\" id=\"s-size\">\r\n");
      out.write("                            <label for=\"s-size\">s</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sc-item\">\r\n");
      out.write("                            <input type=\"radio\" id=\"m-size\">\r\n");
      out.write("                            <label for=\"m-size\">m</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sc-item\">\r\n");
      out.write("                            <input type=\"radio\" id=\"l-size\">\r\n");
      out.write("                            <label for=\"l-size\">l</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sc-item\">\r\n");
      out.write("                            <input type=\"radio\" id=\"xs-size\">\r\n");
      out.write("                            <label for=\"xs-size\">xs</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"filter-widget\">\r\n");
      out.write("                    <h4 class=\"fw-title\">Tags</h4>\r\n");
      out.write("                    <div class=\"fw-tags\">\r\n");
      out.write("                        <a href=\"#\">Quần</a>\r\n");
      out.write("                        <a href=\"#\">Áo</a>\r\n");
      out.write("                        <a href=\"#\">Áo Khoác</a>\r\n");
      out.write("                        <a href=\"#\">Quần kaki</a>\r\n");
      out.write("                        <a href=\"#\">Quần tây</a>\r\n");
      out.write("                        <a href=\"#\">Thắt lưng</a>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-9\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"product-pic-zoom\">\r\n");
      out.write("                            <img class=\"product-big-img\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" alt=\"\">\r\n");
      out.write("                            <div class=\"zoom-icon\">\r\n");
      out.write("                                <i class=\"fa fa-search-plus\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product-thumbs\">\r\n");
      out.write("                            <div class=\"product-thumbs-track ps-slider owl-carousel\">\r\n");
      out.write("                                <div class=\"pt active\" data-imgbigurl=\"img/product-single/product-1.jpg\"><img\r\n");
      out.write("                                        src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" alt=\"\"></div>\r\n");
      out.write("                                <div class=\"pt\" data-imgbigurl=\"img/product-single/product-2.jpg\"><img\r\n");
      out.write("                                        src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" alt=\"\"></div>\r\n");
      out.write("                                <div class=\"pt\" data-imgbigurl=\"img/product-single/product-3.jpg\"><img\r\n");
      out.write("                                        src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" alt=\"\"></div>\r\n");
      out.write("                                <div class=\"pt\" data-imgbigurl=\"img/product-single/product-3.jpg\"><img\r\n");
      out.write("                                        src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\" alt=\"\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"product-details\">\r\n");
      out.write("                            <div class=\"pd-title\">\r\n");
      out.write("                                <span></span>\r\n");
      out.write("                                <h3>Áo khoác kaki</h3>\r\n");
      out.write("                                <a href=\"#\" class=\"heart-icon\"><i class=\"icon_heart_alt\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pd-rating\">\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <span>(5)</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pd-desc\">\r\n");
      out.write("                                <p>Trẻ trung, năng động</p>\r\n");
      out.write("                                <h4>230.000 đ<span>300.000đ</span></h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pd-color\">\r\n");
      out.write("                                <h6>Màu Sắc</h6>\r\n");
      out.write("                                <div class=\"pd-color-choose\">\r\n");
      out.write("                                    <div class=\"cc-item\">\r\n");
      out.write("                                        <input type=\"radio\" id=\"cc-black\">\r\n");
      out.write("                                        <label for=\"cc-black\"></label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"cc-item\">\r\n");
      out.write("                                        <input type=\"radio\" id=\"cc-yellow\">\r\n");
      out.write("                                        <label for=\"cc-yellow\" class=\"cc-yellow\"></label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"cc-item\">\r\n");
      out.write("                                        <input type=\"radio\" id=\"cc-violet\">\r\n");
      out.write("                                        <label for=\"cc-violet\" class=\"cc-violet\"></label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"pd-size-choose\">\r\n");
      out.write("                                <div class=\"sc-item\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"sm-size\">\r\n");
      out.write("                                    <label for=\"sm-size\">s</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"sc-item\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"md-size\">\r\n");
      out.write("                                    <label for=\"md-size\">m</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"sc-item\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"lg-size\">\r\n");
      out.write("                                    <label for=\"lg-size\">l</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"sc-item\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"xl-size\">\r\n");
      out.write("                                    <label for=\"xl-size\">xs</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>Còn lại: <span>1 sản phẩm</span></p>\r\n");
      out.write("             \r\n");
      out.write("                            <div class=\"quantity\">\r\n");
      out.write("                                <div class=\"pro-qty\">\r\n");
      out.write("                                    <input type=\"text\" value=\"1\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"#\" class=\"primary-btn pd-cart\">Thêm vào giỏ</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <ul class=\"pd-tags\">\r\n");
      out.write("                                <li><span>Loại</span>: Áo nữ, Áo kaki</li>\r\n");
      out.write("                                <li><span>TAGS</span>: Quần áo, nữ, kaki</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <div class=\"pd-share\">\r\n");
      out.write("        \r\n");
      out.write("                                <div class=\"pd-social\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"ti-facebook\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"ti-twitter-alt\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"ti-linkedin\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"product-tab\">\r\n");
      out.write("                    <div class=\"tab-item\">\r\n");
      out.write("                        <ul class=\"nav\" role=\"tablist\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"active\" data-toggle=\"tab\" href=\"#tab-1\" role=\"tab\">Mô tả</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("               \r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a data-toggle=\"tab\" href=\"#tab-3\" role=\"tab\">Đánh giá(02)</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tab-item-content\">\r\n");
      out.write("                        <div class=\"tab-content\">\r\n");
      out.write("                            <div class=\"tab-pane fade-in active\" id=\"tab-1\" role=\"tabpanel\">\r\n");
      out.write("                                <div class=\"product-content\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-lg-7\">\r\n");
      out.write("                                         \r\n");
      out.write("                                            <p>Sản phẩm được làm từ chất liệu kaki:</p>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li>Thoáng mát</li>\r\n");
      out.write("                                                <li>Trẻ trung</li>\r\n");
      out.write("                                                <li>Bắt kịp xu hướng</li>\r\n");
      out.write("                                               \r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-lg-5\">\r\n");
      out.write("                                            <img src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\" alt=\"\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"tab-pane fade\" id=\"tab-3\" role=\"tabpanel\">\r\n");
      out.write("                                <div class=\"customer-review-option\">\r\n");
      out.write("                                    <h4>2 Bình luận</h4>\r\n");
      out.write("                                    <div class=\"comment-option\">\r\n");
      out.write("                                        <div class=\"co-item\">\r\n");
      out.write("                                            \r\n");
      out.write("                                            <div class=\"avatar-text\">\r\n");
      out.write("                                                <div class=\"at-rating\">\r\n");
      out.write("                                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <h5>Thành Long <span>2/11/2020</span></h5>\r\n");
      out.write("                                                <div class=\"at-reply\">Tuyệt vời !</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"co-item\">\r\n");
      out.write("                                           \r\n");
      out.write("                                            <div class=\"avatar-text\">\r\n");
      out.write("                                                <div class=\"at-rating\">\r\n");
      out.write("                                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                                    <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <h5>Minh Đạt <span>10/11/2020</span></h5>\r\n");
      out.write("                                                <div class=\"at-reply\">Sản phẩm rất tốt !</div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"personal-rating\">\r\n");
      out.write("                                        <h6>Đánh giá của bạn</h6>\r\n");
      out.write("                                        <div class=\"rating\">\r\n");
      out.write("                                            <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                            <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"leave-comment\">\r\n");
      out.write("                                        <h4>Bình luận</h4>\r\n");
      out.write("                                        <form action=\"#\" class=\"comment-form\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-lg-12\">\r\n");
      out.write("                                                    <textarea placeholder=\"Bình luận\"></textarea>\r\n");
      out.write("                                                    <button type=\"submit\" class=\"site-btn\">Gửi</button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- Product Shop Section End -->\r\n");
      out.write("\r\n");
      out.write("<!-- Related Products Section End -->\r\n");
      out.write("<div class=\"related-products spad\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("                <div class=\"section-title\">\r\n");
      out.write("                    <h2>Sản phẩm liên quan</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-pic\">\r\n");
      out.write("                        <img src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\" alt=\"\">\r\n");
      out.write("                        <div class=\"sale\">Sale</div>\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                            <i class=\"icon_heart_alt\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li class=\"w-icon active\"><a href=\"#\"><i class=\"icon_bag_alt\"></i></a></li>\r\n");
      out.write("                            <li class=\"quick-view\"><a href=\"#\">+ Quick View</a></li>\r\n");
      out.write("                            <li class=\"w-icon\"><a href=\"#\"><i class=\"fa fa-random\"></i></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"pi-text\">\r\n");
      out.write("                        <div class=\"catagory-name\">Coat</div>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <h5>Pure Pineapple</h5>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"product-price\">\r\n");
      out.write("                            $14.00\r\n");
      out.write("                            <span>$35.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-pic\">\r\n");
      out.write("                        <img src=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\" alt=\"\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                            <i class=\"icon_heart_alt\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li class=\"w-icon active\"><a href=\"#\"><i class=\"icon_bag_alt\"></i></a></li>\r\n");
      out.write("                            <li class=\"quick-view\"><a href=\"#\">+ Quick View</a></li>\r\n");
      out.write("                            <li class=\"w-icon\"><a href=\"#\"><i class=\"fa fa-random\"></i></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"pi-text\">\r\n");
      out.write("                        <div class=\"catagory-name\">Shoes</div>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <h5>Guangzhou sweater</h5>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"product-price\">\r\n");
      out.write("                            $13.00\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-pic\">\r\n");
      out.write("                        <img src=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\" alt=\"\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                            <i class=\"icon_heart_alt\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li class=\"w-icon active\"><a href=\"#\"><i class=\"icon_bag_alt\"></i></a></li>\r\n");
      out.write("                            <li class=\"quick-view\"><a href=\"#\">+ Quick View</a></li>\r\n");
      out.write("                            <li class=\"w-icon\"><a href=\"#\"><i class=\"fa fa-random\"></i></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"pi-text\">\r\n");
      out.write("                        <div class=\"catagory-name\">Towel</div>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <h5>Pure Pineapple</h5>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"product-price\">\r\n");
      out.write("                            $34.00\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-pic\">\r\n");
      out.write("                        <img src=\"");
      if (_jspx_meth_c_005furl_005f10(_jspx_page_context))
        return;
      out.write("\" alt=\"\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                            <i class=\"icon_heart_alt\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li class=\"w-icon active\"><a href=\"#\"><i class=\"icon_bag_alt\"></i></a></li>\r\n");
      out.write("                            <li class=\"quick-view\"><a href=\"#\">+ Quick View</a></li>\r\n");
      out.write("                            <li class=\"w-icon\"><a href=\"#\"><i class=\"fa fa-random\"></i></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"pi-text\">\r\n");
      out.write("                        <div class=\"catagory-name\">Towel</div>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <h5>Converse Shoes</h5>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"product-price\">\r\n");
      out.write("                            $34.00\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Related Products Section End -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /view/web/product-details.jsp(18,31) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/view/web/index.jsp");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /view/web/product-details.jsp(162,62) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/template/web/img/product-single/product-1.jpg");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /view/web/product-details.jsp(170,45) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/template/web/img/product-single/product-1.jpg");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /view/web/product-details.jsp(172,45) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/template/web/img/product-single/product-2.jpg");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /view/web/product-details.jsp(174,45) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/template/web/img/product-single/product-3.jpg");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /view/web/product-details.jsp(176,45) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/template/web/img/product-single/product-3.jpg");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /view/web/product-details.jsp(286,54) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/template/web/img/product-single/product-1.jpg");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /view/web/product-details.jsp(371,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/template/web/img/products/women-1.jpg");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /view/web/product-details.jsp(397,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/template/web/img/products/women-2.jpg");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /view/web/product-details.jsp(421,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/template/web/img/products/women-3.jpg");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent(null);
      // /view/web/product-details.jsp(445,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue("/template/web/img/products/women-4.jpg");
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }
}
