/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-11-18 03:28:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.admin.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_002dproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1605004395856L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1599801223744L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/ecommerce/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ecommerce/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1599801224031L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/ecommerce/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ecommerce/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Thêm sản phẩm</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h3 class=\"ml-4 mt-3\">Thêm sản phẩm</h3>\r\n");
      out.write("\t<form action=\"\" class=\"p-5\">\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"exampleFormControlInput1\">Mã sản phẩm</label> <input\r\n");
      out.write("\t\t\t\ttype=\"text\" class=\"form-control\" id=\"exampleFormControlInput1\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Mã sản phẩm\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"exampleFormControlInput1\">Tên sản phẩm</label> <input\r\n");
      out.write("\t\t\t\ttype=\"text\" class=\"form-control\" id=\"exampleFormControlInput1\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Tên sản phẩm\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"exampleFormControlInput1\" class=\"d-block\">Mô tả sản phẩm</label> \r\n");
      out.write("\t\t\t<textarea rows=\"5\" cols=\"50\" name=\"description\"></textarea>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"exampleFormControlInput1\">Hình ảnh sản phẩm</label> <input\r\n");
      out.write("\t\t\t\ttype=\"file\" class=\"form-control\" id=\"exampleFormControlInput1\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Hình ảnh sản phẩm\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"exampleFormControlSelect1\">Phân loại</label> <select\r\n");
      out.write("\t\t\t\tclass=\"form-control\" id=\"exampleFormControlSelect1\">\r\n");
      out.write("\t\t\t\t<option>Chọn--</option>\r\n");
      out.write("\t\t\t\t<optgroup label=\"Nam\">\r\n");
      out.write("\t\t\t\t\t<optgroup label=\"&nbsp;&nbsp;&nbsp;&nbsp;Quần\">\r\n");
      out.write("\t\t\t\t\t\t<option>&nbsp;&nbsp;&nbsp;&nbsp;Kaki</option>\r\n");
      out.write("\t\t\t\t\t\t<option>&nbsp;&nbsp;&nbsp;&nbsp;Tây</option>\r\n");
      out.write("\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t<optgroup label=\"&nbsp;&nbsp;&nbsp;&nbsp;Áo\">\r\n");
      out.write("\t\t\t\t\t\t<option>&nbsp;&nbsp;&nbsp;&nbsp;Thun</option>\r\n");
      out.write("\t\t\t\t\t\t<option>&nbsp;&nbsp;&nbsp;&nbsp;Sơ mi</option>\r\n");
      out.write("\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t<optgroup label=\"&nbsp;&nbsp;&nbsp;&nbsp;Phụ kiện\">\r\n");
      out.write("\t\t\t\t\t\t<option>&nbsp;&nbsp;&nbsp;&nbsp;Ví</option>\r\n");
      out.write("\t\t\t\t\t\t<option>&nbsp;&nbsp;&nbsp;&nbsp;Thắt lưng</option>\r\n");
      out.write("\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t<optgroup label=\"Nữ\">\r\n");
      out.write("\t\t\t\t\t<optgroup  label=\"&nbsp;&nbsp;&nbsp;&nbsp;Quần\">\r\n");
      out.write("\t\t\t\t\t\t<option>&nbsp;&nbsp;&nbsp;&nbsp;Kaki</option>\r\n");
      out.write("\t\t\t\t\t\t<option>&nbsp;&nbsp;&nbsp;&nbsp;Tây</option>\r\n");
      out.write("\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t<optgroup label=\"&nbsp;&nbsp;&nbsp;&nbsp;Áo\">\r\n");
      out.write("\t\t\t\t\t\t<option>&nbsp;&nbsp;&nbsp;&nbsp;Thun</option>\r\n");
      out.write("\t\t\t\t\t\t<option>&nbsp;&nbsp;&nbsp;&nbsp;Sơ mi</option>\r\n");
      out.write("\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t\t<optgroup  label=\"&nbsp;&nbsp;&nbsp;&nbsp;Phụ kiện\">\r\n");
      out.write("\t\t\t\t\t\t<option>&nbsp;&nbsp;&nbsp;&nbsp;Ví</option>\r\n");
      out.write("\t\t\t\t\t\t<option>&nbsp;&nbsp;&nbsp;&nbsp;Khăn</option>\r\n");
      out.write("\t\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t\t</optgroup>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group\" id=\"attribute\">\r\n");
      out.write("\t\t\t<label for=\"exampleFormControlSelect2\" style=\"margin-right: 120px;\">Kích\r\n");
      out.write("\t\t\t\tcỡ, Màu sắc, Số lượng</label>\r\n");
      out.write("\t\t\t\t<select id=\"warehouse\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>Kho</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>A</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>B</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>C</option>\r\n");
      out.write("\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t<select class=\"ml-2\" id=\"shelves\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>Kệ</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Ảo</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>1A</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>1B</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>2A</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>2B</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t<ul id=\"size_color_quantity\">\r\n");
      out.write("\t\t\t\t<!-- <li id=\"line\">\r\n");
      out.write("\t\t\t\t\t<select id=\"size\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>S</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>M</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>L</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>XL</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>XXL</option>\r\n");
      out.write("\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t<select id=\"color\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>Đỏ</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Vàng</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Tím</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Trắng</option>\r\n");
      out.write("\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t<input class=\"mr-5\" type=\"text\" id=\"quntity\" name='quantity'>\r\n");
      out.write("\t\t\t\t\t<select id=\"warehouse\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>A</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>B</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>C</option>\r\n");
      out.write("\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t<select class=\"ml-3\" id=\"shelves\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>Ảo</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>1A</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>1B</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>2A</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>2B</option>\r\n");
      out.write("\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<a style=\"color: white; text-decoration: none; width: 100px;\"\r\n");
      out.write("\t\t\t\t\tid=\"addLine\" type=\"button\" class=\"btn btn-secondary ml-5 mt-2 mb-3\">Thêm<i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-plus ml-2\"></i></a>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t\t\t$('#addLine').on('click', function(event) {\r\n");
      out.write("\t\t\t\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t\t\t\t$('#size_color_quantity').append('<li class=\"mt-1\"><select id=\"size\"><option>S</option><option>M</option><option>L</option><option>XL</option><option>XXL</option></select><select id=\"color\"><option>Đỏ</option><option>Vàng</option><option>Tím</option><option>Trắng</option></select> <input class=\"mr-5\" type=\"text\" id=\"quantity\" name=\"quantity\"><select id=\"warehouse\"><option>A</option><option>B</option><option>C</option></select><select class=\"ml-3\" id=\"shelves\"><option>Ảo</option><option>1A</option><option>1B</option><option>2A</option><option>2B</option></select></li>'); \r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"exampleFormControlSelect3\">Thương hiệu</label> <select\r\n");
      out.write("\t\t\t\tclass=\"form-control\" id=\"exampleFormControlSelect3\">\r\n");
      out.write("\t\t\t\t<option>Chọn--</option>\r\n");
      out.write("\t\t\t\t<option>Yame</option>\r\n");
      out.write("\t\t\t\t<option>Routine</option>\r\n");
      out.write("\t\t\t\t<option>Ben</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"exampleFormControlInput1\">Gía niêm yết</label> <input\r\n");
      out.write("\t\t\t\ttype=\"text\" class=\"form-control\" id=\"exampleFormControlInput1\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Nhập giá niêm yết\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"exampleFormControlSelect2\">Trạng thái</label> \r\n");
      out.write("\t\t\t<select class=\"form-control\" id=\"status\">\r\n");
      out.write("\t\t\t\t<option selected=\"selected\" disabled=\"disabled\">Hàng mới</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<a style=\"color: white; text-decoration: none; width: 20%;\"\r\n");
      out.write("\t\thref=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" type=\"button\"\r\n");
      out.write("\t\tclass=\"btn btn-info ml-5 mb-3\"> Thêm sản phẩm </a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /view/admin/product/add-product.jsp(153,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/view/admin/add-product.jsp");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
