/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-11-18 04:51:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.admin.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_002dproduct_002dgroup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1605004395856L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1599801223744L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/ecommerce/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ecommerce/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1599801224031L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/ecommerce/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ecommerce/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Nhóm sản phẩm</title>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h3 class=\"ml-4 mt-3 mb-3 d-inline\">Nhóm sản phẩm</h3>\r\n");
      out.write("\t<a style=\"text-decoration: none;\"\r\n");
      out.write("\t\thref=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\ttype=\"button\" class=\"btn btn-info\"> Thêm nhóm sản phẩm <i\r\n");
      out.write("\t\tclass=\"fa fa-plus ml-2\"></i>\r\n");
      out.write("\t</a>\r\n");
      out.write("\t<h4 class=\"ml-4 mt-5 mb-2\">Đối tượng Khách Hàng (Nhóm sản phẩm Bậc\r\n");
      out.write("\t\t1)</h4>\r\n");
      out.write("\t<div class=\"\">\r\n");
      out.write("\t\t<table class=\"table text-center\">\r\n");
      out.write("\t\t\t<thead class=\"thead-dark\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Xóa</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Cập nhật</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">ID</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Tên nhóm khách hàng</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody class=\"scrollDiv\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">1</th>\r\n");
      out.write("\t\t\t\t\t<td>Nam</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">2</th>\r\n");
      out.write("\t\t\t\t\t<td>Nữ</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">3</th>\r\n");
      out.write("\t\t\t\t\t<td>Trẻ em</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"btn-control ml-2 mb-2\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-danger\">\r\n");
      out.write("\t\t\tXóa<i class=\"fa fa-trash ml-2\"></i>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-danger\">\r\n");
      out.write("\t\t\tXóa tất cả<i class=\"fa fa-trash  ml-2\"></i>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<h4 class=\"ml-4 mt-5 mb-2\">Danh mục sản phẩm (Nhóm sản phẩm Bậc 2)</h4>\r\n");
      out.write("\t<div class=\"scrollDiv\">\r\n");
      out.write("\t\t<table class=\"table text-center\">\r\n");
      out.write("\t\t\t<thead class=\"thead-dark\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Xóa</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Cập nhật</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">ID</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Tên nhóm danh mục</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Tên nhóm khách hàng</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody class=\"scrollDiv\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">4</th>\r\n");
      out.write("\t\t\t\t\t<td>Quần</td>\r\n");
      out.write("\t\t\t\t\t<td>Nam</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">5</th>\r\n");
      out.write("\t\t\t\t\t<td>Áo</td>\r\n");
      out.write("\t\t\t\t\t<td>Nam</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">6</th>\r\n");
      out.write("\t\t\t\t\t<td>Phụ kiện</td>\r\n");
      out.write("\t\t\t\t\t<td>Nam</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">7</th>\r\n");
      out.write("\t\t\t\t\t<td>Quần</td>\r\n");
      out.write("\t\t\t\t\t<td>Nữ</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">8</th>\r\n");
      out.write("\t\t\t\t\t<td>Áo</td>\r\n");
      out.write("\t\t\t\t\t<td>Nữ</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">9</th>\r\n");
      out.write("\t\t\t\t\t<td>Phụ kiện</td>\r\n");
      out.write("\t\t\t\t\t<td>Nữ</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">10</th>\r\n");
      out.write("\t\t\t\t\t<td>Quần</td>\r\n");
      out.write("\t\t\t\t\t<td>Trẻ em</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">11</th>\r\n");
      out.write("\t\t\t\t\t<td>Áo</td>\r\n");
      out.write("\t\t\t\t\t<td>Trẻ em</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"btn-control ml-2 mb-2\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-danger\">\r\n");
      out.write("\t\t\tXóa<i class=\"fa fa-trash ml-2\"></i>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-danger\">\r\n");
      out.write("\t\t\tXóa tất cả<i class=\"fa fa-trash  ml-2\"></i>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<h4 class=\"ml-4 mt-5 mb-2\">Loại sản phẩm (Nhóm sản phẩm Bậc 3)</h4>\r\n");
      out.write("\t<div class=\"scrollDiv\">\r\n");
      out.write("\t\t<table class=\"table text-center\">\r\n");
      out.write("\t\t\t<thead class=\"thead-dark\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Xóa</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Cập nhật</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">ID</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Tên nhóm loại</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Tên nhóm danh mục</th>\r\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Tên nhóm khách hàng</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody class=\"scrollDiv\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">12</th>\r\n");
      out.write("\t\t\t\t\t<td>Quần kaki</td>\r\n");
      out.write("\t\t\t\t\t<td>Quần</td>\r\n");
      out.write("\t\t\t\t\t<td>Nam</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">13</th>\r\n");
      out.write("\t\t\t\t\t<td>Quần tây</td>\r\n");
      out.write("\t\t\t\t\t<td>Quần</td>\r\n");
      out.write("\t\t\t\t\t<td>Nam</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">14</th>\r\n");
      out.write("\t\t\t\t\t<td>Áo thun</td>\r\n");
      out.write("\t\t\t\t\t<td>Áo</td>\r\n");
      out.write("\t\t\t\t\t<td>Nam</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">15</th>\r\n");
      out.write("\t\t\t\t\t<td>Áo sơ mi</td>\r\n");
      out.write("\t\t\t\t\t<td>Áo</td>\r\n");
      out.write("\t\t\t\t\t<td>Nam</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">16</th>\r\n");
      out.write("\t\t\t\t\t<td>Ví</td>\r\n");
      out.write("\t\t\t\t\t<td>Phụ kiện</td>\r\n");
      out.write("\t\t\t\t\t<td>Nam</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">17</th>\r\n");
      out.write("\t\t\t\t\t<td>Thắt lưng</td>\r\n");
      out.write("\t\t\t\t\t<td>Phụ kiện</td>\r\n");
      out.write("\t\t\t\t\t<td>Nam</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">18</th>\r\n");
      out.write("\t\t\t\t\t<td>Quần kaki</td>\r\n");
      out.write("\t\t\t\t\t<td>Quần</td>\r\n");
      out.write("\t\t\t\t\t<td>Nữ</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">19</th>\r\n");
      out.write("\t\t\t\t\t<td>Quần tây</td>\r\n");
      out.write("\t\t\t\t\t<td>Quần</td>\r\n");
      out.write("\t\t\t\t\t<td>Nữ</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">20</th>\r\n");
      out.write("\t\t\t\t\t<td>Áo thun</td>\r\n");
      out.write("\t\t\t\t\t<td>Áo</td>\r\n");
      out.write("\t\t\t\t\t<td>Nữ</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">21</th>\r\n");
      out.write("\t\t\t\t\t<td>Áo sơ mi</td>\r\n");
      out.write("\t\t\t\t\t<td>Áo</td>\r\n");
      out.write("\t\t\t\t\t<td>Nữ</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">22</th>\r\n");
      out.write("\t\t\t\t\t<td>Ví</td>\r\n");
      out.write("\t\t\t\t\t<td>Phụ kiện</td>\r\n");
      out.write("\t\t\t\t\t<td>Nữ</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">23</th>\r\n");
      out.write("\t\t\t\t\t<td>Khăn</td>\r\n");
      out.write("\t\t\t\t\t<td>Phụ kiện</td>\r\n");
      out.write("\t\t\t\t\t<td>Nữ</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">24</th>\r\n");
      out.write("\t\t\t\t\t<td>Quần kaki</td>\r\n");
      out.write("\t\t\t\t\t<td>Quần</td>\r\n");
      out.write("\t\t\t\t\t<td>Trẻ em</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">25</th>\r\n");
      out.write("\t\t\t\t\t<td>Quần tây</td>\r\n");
      out.write("\t\t\t\t\t<td>Quần</td>\r\n");
      out.write("\t\t\t\t\t<td>Trẻ em</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">26</th>\r\n");
      out.write("\t\t\t\t\t<td>Áo thun</td>\r\n");
      out.write("\t\t\t\t\t<td>Áo</td>\r\n");
      out.write("\t\t\t\t\t<td>Trẻ em</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"checkbox\" name=\"delete\"></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"\"><i class=\"fa fa-edit\"></i></a></i></td>\r\n");
      out.write("\t\t\t\t\t<th scope=\"row\">27</th>\r\n");
      out.write("\t\t\t\t\t<td>Áo sơ mi</td>\r\n");
      out.write("\t\t\t\t\t<td>Áo</td>\r\n");
      out.write("\t\t\t\t\t<td>Trẻ em</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"btn-control ml-2 mb-2\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-danger\">\r\n");
      out.write("\t\t\tXóa<i class=\"fa fa-trash ml-2\"></i>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-danger\">\r\n");
      out.write("\t\t\tXóa tất cả<i class=\"fa fa-trash  ml-2\"></i>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /view/admin/product/list-product-group.jsp(10,6) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/template/admin/assets/plugins/jquery/jquery.min.js");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /view/admin/product/list-product-group.jsp(15,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/view/admin/product/add-product-group.jsp");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
